### ISSUE TITLE
After every restart HA I have to manually do Relod in integration entries. Otherwise entity is no longer being provided by the blinds_controller integration.

### ISSUE THREAD

**Issue by petr314** [MatthewOnTour/BUT_blinds_time_control#6]
Relod helps in integration menu

**Comment by petr314** [comment]
Logger: homeassistant.components.cover
Source: helpers/entity_platform.py:364
integration: Cover (documentation, issues)
First occurred: 22:53:13 (1 occurrences)
Last logged: 22:53:13

Error while setting up blinds_controller platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/blinds_controller/cover.py", line 65, in async_setup_entry
    async_add_entities([BlindsCover(hass, entry, name, device_id)])
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/blinds_controller/cover.py", line 100, in __init__
    self._wind_speed = self.hass.states.get(self._netamo_speed_entity).state
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'state'

**Comment by petr314** [comment]
The problem was setting the Netatmo option in this integration due to the above error. So do not set up Netatmo inside this integration to protect blinds until the bug is fixed. You should uninstall and reinstall BUT_blinds_time_control to set the wind speed and wind gust speed entities to null and then everything works perfectly without any problems.
Big thanks to the author for this integration.
